### PR TITLE
Add a Basic PodSpec. It misses the dependencies and some more details

### PR DESCRIPTION
**Pull request by racer1988**
Start of Feature Request for #44

### CODE REVIEW

**Comment by maticzav** [comment]
@racer1988 could you maybe reference any samples so I can finish this? I think this could be really beneficial for many people.

**Comment by Amzd** [comment]
We had a working PodSpec file for SwiftGraphQL at my previous company. I can inquire if they would open source it.

**Comment by maticzav** [comment]
I started playing with this a bit, but then there are many Podspecs that don't list dependencies and then something came and I didn't finish.

@Amzd if you can try getting, that would be 🤯

**Comment by maticzav** [comment]
The new version of SwiftGraphQL ships with a Podspec. Thank you for opening this PR! 🚀

**Pull request closed without merging**
