### PR TITLE
Bump iOS Version + small doc improvement

### LINKED ISSUE #136: Error installing 5.0.1
**Describe the bug**
It not installs on fresh project with 5.0.1.

**To Reproduce**

1. Create a fresh project
2. Add `https://github.com/maticzav/swift-graphql/`

image

**Expected behavior**
Should install with success

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: macOs, iOS, XCode
- Version: 13.3 / 16.4 / 14.3

image

### PR DESCRIPTION
**Pull request by robsontenorio**
Fix #136 

- Set version to iOS16
- Small doc update

### CODE REVIEW

**Comment by maticzav** [comment]
I see that you tested other versions as well! Does it not work with `v14`? I am hesitant to make such a huge version jump unless it's necessary.

**Comment by robsontenorio** [comment]
@maticzav as you can see on #136 screenshots v15 is necessary for some functions.

**Comment by maticzav** [comment]
Hey, I tried running tests on iOS 15 (in the CI, sorry) and went ahead and merged it to unblock you. Let me know if I missed something and we should have instead used iOS 16 as a base.

Thank you for opening a PR! ❤️

**Comment by robsontenorio** [comment]
@maticzav  yes, v15 is enough for a while. Thanks!

**Comment by maticzav** [comment]
To give a bit more context to why I decided that we can safely bump the version; considering iOS installation charts, it seems like almost no iPhone relies on iOS 14 anymore [statista.com/statistics/565270/apple-devices-ios-version-share-worldwide](https://www.statista.com/statistics/565270/apple-devices-ios-version-share-worldwide/).

SwiftGraphQL relies on certain APIs that rely on iOS 15, though if I recall correctly, they may be substituted for alternatives that have better legacy support. In case you need to support older versions of iOS, please open an issue thoroughly explaining your case and the constraints that you have to work around.

**Pull request merged**
