### PR TITLE
test: implement test cases for closing and reconnecting WebSocket

### PR DESCRIPTION
**Pull request by pokryfka**

### CODE REVIEW

**Comment by shaps80** [comment]
@pokryfka I'll review properly later this week, I've been sick for a couple days.

I also appreciate that you've included tests, but why in a separate PR? I'd prefer this was self-contained tbh.

**Comment by pokryfka** [comment]
> @pokryfka I'll review properly later this week, I've been sick for a couple days.

No worries, I am happy to help to add momentum to the project but I dont think I will start using it in production any time soon, so none of it is urgent.

FYI I will be offline for 1.5 weeks from Oct 28, will check your comments after I am back.

> I also appreciate that you've included tests, but why in a separate PR? I'd prefer this was self-contained tbh.

I think additional tests add value regardless if and when WebSocket refactoring is merged.
Ideally test cases should be implemented before any refactoring (and arguably even before implementation is finished), not after or during, to make sure the expected behaviour remained the same.

I can merge it to #180 if you prefer.

**Comment by shaps80** [comment]
> I think additional tests add value regardless if and when WebSocket refactoring is merged.

Of course.

> Ideally test cases should be implemented before any refactoring (and arguably even before implementation is finished), not after or during, to make sure the expected behaviour remained the same.

I respectfully disagree. That's just one approach (TDD I guess you're referring to), its not he only or even necessarily "ideal" approach. It's very much a personal approach in my 25 years of experience I've seen various approaches and have no evidence in practice of any approach leading to more testable or more important reliable and robust code.

Generally the issue is a lack of understanding how to write quality tests, not "when" you wrote the tests 👍

Just my two cents 😉

**Comment by shaps80** [comment]
> I can merge it to #180 if you prefer.

100% I think that's the right way to review this. I 100% agree with you, adding tests here is extremely important 👍

Thanks again!

**Comment by shaps80** [comment]
If you can merge these changes into the other branch that would be great, I'll close this here since you can sort that separately thank you!

**Pull request closed without merging**
